title: ARCADE Website
description: "ARCADE: Scalable Demonstration Collection and Generation via Augmented Reality for Imitation Learning"
# A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://yy-gx.github.io/ARCADE

aux_links:
  ARCADE on Github: https://github.com/YY-GX/ARCADE-Codebase

favicon_ico: "/assets/images/logo.ico"
