title: ARCADE Website
description: The website for the IROS 24' conference paper: "ARCADE: Scalable Demonstration Collection and Generation via Augmented Reality for Imitation Learning".
theme: just-the-docs

url: https://YY-GX.github.io/ARCADE

# aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
